version: '3.8'
services:
  app:
    build:
      context: ./back_end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_DATABASE: iv1201db   
      DB_USERNAME: postgres      
      DB_PASSWORD: password123     
      DB_HOST: postgres            
      DB_PORT: 5432                
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: iv1201db          
      POSTGRES_USER: postgres        
      POSTGRES_PASSWORD: password123 
    ports:
      - "5432:5432"
    volumes:
      - ./back_end/initdb:/docker-entrypoint-initdb.d/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
