name: Node.js CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache npm dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('./back_end/package-lock.json') }}
        restore-keys: |
          npm-

    - name: Install dependencies
      run: npm ci
      working-directory: ./back_end

    - name: Run ESLint
      run: npm run lint
      working-directory: ./back_end
    - name: Run Tests
      run: npm test
      working-directory: ./back_end